# Generated by Django 5.0.9 on 2025-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacomptable', '0002_remove_associe_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratpersonnemorale',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='contratpersonnemorale',
            name='lieu_naissance_representant',
        ),
        migrations.RemoveField(
            model_name='contratpersonnemorale',
            name='nom_mere_representant',
        ),
        migrations.RemoveField(
            model_name='contratpersonnemorale',
            name='nom_pere_representant',
        ),
        migrations.RemoveField(
            model_name='contratpersonnephysique',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='contratpersonnephysique',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='contratpersonnephysique',
            name='nom_pere',
        ),
        migrations.AddField(
            model_name='contratpersonnemorale',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
    ]
